# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(null=True, upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('picture', models.ImageField(null=True, upload_to=b'images/')),
                ('map', models.ImageField(null=True, upload_to=b'images/')),
                ('gmap_url', models.CharField(max_length=200, null=True)),
                ('votes', models.IntegerField(choices=[(1, b'one'), (2, b'two'), (3, b'three'), (4, b'four')], default=4)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Town'),
        ),
    ]
