# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20181211_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='food',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='town',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
